alg: dtw #lstm #htm, dtw, edr, arima
test_mode: batch #batch, online
train_models: true #true, false
hz: 10
window_size: 1
data_cap: 1000000
scaling: false  #false, minmax, standard

test_indices:
  - 1
  - 2
  - 3

features:
  - xs
  - ys
  - zs
  - dists

algs_types:
  lstm: prediction
  arima: prediction
  htm: anomaly
  dtw: distance
  edr: distance

colinds_features:
  '0.3': xs
  '0.4': ys
  '0.5': zs
  '0.8': dists_x
  '0.9': dists_y
  '0.10': dists_z
  '0': dists

dirs:
  input: /Users/samheiserman/Desktop/PhD/Motion-Print/data/subjects_raw
  output_data: /Users/samheiserman/Desktop/PhD/Motion-Print/data/subjects_preprocessed
  output_models: /Users/samheiserman/Desktop/PhD/Motion-Print/output/models
  output_scalers: /Users/samheiserman/Desktop/PhD/Motion-Print/output/scalers
  output_results: /Users/samheiserman/Desktop/PhD/Motion-Print/output/rank_scores

lstm_config:
  n_epochs: 100
  n_layers: 2
  n_units: 100
  activation: relu
  optimizer: adam
  loss: mse

arima_config:
  start_p: 2
  start_P: 1
  start_q: 2
  start_Q: 1
  max_p: 5
  max_d: 2
  max_q: 5
  max_P: 2
  max_D: 1
  max_Q: 2
  m: 1
  max_order: 5
  scoring: mse

htm_config:
  features:
    - xs
    - ys
    - zs
    - dists
  models_encoders:
    minmax_percentiles:
      - 1
      - 99
    n: 700
    n_buckets: 140
    sparsity: 0.05  #0.02
    timestamp:
      enable: false
      feature: satellite_time
      timeOfDay:
        - 30
        - 1
      weekend: 21
  models_params:
    anomaly:
      period: 1000
    predictor:
      sdrc_alpha: 0.1
    sp:
      boostStrength: 2.0
      columnCount: 2048
      localAreaDensity: 0.04395604395604396
      potentialPct: 0.8
      synPermActiveInc: 0.05  #0.003
      synPermConnected: 0.1  #0.2
      synPermInactiveDec: 0.085  #0.0005
    tm:
      activationThreshold: 13
      cellsPerColumn: 32
      initialPerm: 0.21
      maxSegmentsPerCell: 128
      maxSynapsesPerSegment: 32
      minThreshold: 10
      newSynapseCount: 20
      permanenceConnected: 0.3
      permanenceDec: 0.1
      permanenceInc: 0.1
  models_state:
    model_for_each_feature: false
    save_outputs_accumulated: true
    use_sp: false
    track_iter: 10
    track_tm: false
  timesteps_stop:
    learning: 100000
    running: 110000
    sampling: 30
